version: "3.9"
services:
  frontend:
    container_name: nike-landing-page
    image: nike-landing-page/v1.0.0
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - frontend
    ports:
      - "8080:80"

networks:
  frontend:
    name: nike-landing-page